# Generated by Django 3.0.8 on 2020-09-17 13:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceOfWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('budget', models.IntegerField(default=0)),
                ('dtStart', models.DateField(default=datetime.datetime(2020, 9, 17, 13, 44, 29, 793303, tzinfo=utc))),
                ('dtEnd', models.DateField(default=datetime.datetime(2020, 9, 17, 13, 44, 29, 793303, tzinfo=utc))),
                ('title', models.TextField(default='sans titre', help_text="Titre de l'oeuvre, même temporaire")),
                ('nature', models.CharField(choices=[('MOVIE', 'Film long métrage'), ('COURT', 'Court métrage'), ('PUB', 'Publicité'), ('CORP', "Film d'entreprise"), ('SONG', 'Single/Album')], default='MOVIE', max_length=20)),
                ('url', models.URLField(default='', null=True)),
                ('imdb', models.URLField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=70)),
                ('lastname', models.CharField(default='', max_length=70)),
                ('birthdate', models.DateField(null=True)),
                ('nationality', models.CharField(default='Française', max_length=30)),
                ('department', models.CharField(max_length=30, null=True)),
                ('degree_year', models.IntegerField(null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('photo', models.URLField(blank=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('linkedin', models.URLField(blank=True)),
                ('cp', models.IntegerField(null=True)),
                ('website', models.URLField(null=True)),
            ],
            options={
                'ordering': ['lastname'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dtStart', models.DateField(default=datetime.datetime(2020, 9, 17, 13, 44, 29, 793303, tzinfo=utc))),
                ('dtEnd', models.DateField(default=datetime.datetime(2020, 9, 17, 13, 44, 29, 793303, tzinfo=utc))),
                ('status', models.CharField(default='', max_length=200)),
                ('job', models.CharField(default='', max_length=200)),
                ('duration', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=400)),
                ('pow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='alumni.PieceOfWork')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='alumni.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(blank=True, default='', max_length=500)),
                ('canSponsor', models.BooleanField(default=False)),
                ('profil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.Profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extrauser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
