# Generated by Django 3.0.8 on 2020-09-17 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 13, 45, 23, 457734, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 13, 45, 23, 457734, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 13, 45, 23, 457734, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 13, 45, 23, 457734, tzinfo=utc)),
        ),
    ]
