# Generated by Django 3.2 on 2021-04-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofwork',
            name='apiVideoId',
            field=models.CharField(blank=True, default='', help_text='Version stocké sur api.video', max_length=20),
        ),
    ]
