# Generated by Django 3.0.8 on 2020-09-17 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20200917_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='mobile',
            field=models.CharField(default='06', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 14, 44, 7, 261458, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 14, 44, 7, 261458, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 14, 44, 7, 260553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 17, 14, 44, 7, 260553, tzinfo=utc)),
        ),
    ]
