# Generated by Django 3.0.8 on 2020-09-18 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20200917_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofwork',
            name='text_url',
            field=models.CharField(default="plus d'info", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 12, 31, 59, 170511, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 12, 31, 59, 170511, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 12, 31, 59, 169510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 12, 31, 59, 169510, tzinfo=utc)),
        ),
    ]
