# Generated by Django 3.2 on 2021-06-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_profil_blockchain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='blockchain',
            field=models.CharField(blank=True, default='', help_text='Adresse elrond du profil', max_length=50),
        ),
    ]
