# Generated by Django 3.0.8 on 2020-09-18 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_auto_20200918_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrauser',
            old_name='tags',
            new_name='perm',
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 15, 49, 9, 964807, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 15, 49, 9, 964807, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 15, 49, 9, 963824, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 18, 15, 49, 9, 963824, tzinfo=utc)),
        ),
    ]
