# Generated by Django 3.0.8 on 2020-09-21 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20200918_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 10, 13, 49, 604850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 10, 13, 49, 604850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 10, 13, 49, 604850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 10, 13, 49, 604850, tzinfo=utc)),
        ),
    ]
