# Generated by Django 3.2 on 2021-06-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_profil_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('siret', models.CharField(default='', max_length=14)),
                ('address', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
