# Generated by Django 3.0.8 on 2020-09-21 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_auto_20200921_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauser',
            name='black_list',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 11, 1, 17, 332783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 11, 1, 17, 332783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 11, 1, 17, 332783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 21, 11, 1, 17, 332783, tzinfo=utc)),
        ),
    ]
