# Generated by Django 3.2 on 2021-07-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_profil_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='dtLastSearch',
            field=models.DateTimeField(default=0, help_text="Date de la dernière recherche d'expérience pour le profil"),
        ),
    ]
