# Generated by Django 3.0.8 on 2020-09-22 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_auto_20200921_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='black_list',
            field=models.TextField(default='', help_text="Contient l'ensemble des emails ne pouvant contacter la personne"),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 9, 10, 6, 884002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 9, 10, 6, 884002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='comment',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 9, 10, 6, 882989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 9, 10, 6, 882989, tzinfo=utc)),
        ),
    ]
