# Generated by Django 3.0.8 on 2020-09-22 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_auto_20200922_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtEnd',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 9, 59, 33, 481657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtStart',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 9, 59, 33, 481657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtEnd',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtStart',
            field=models.DateField(auto_now=True),
        ),
    ]
