# Generated by Django 3.0.8 on 2020-09-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0011_auto_20200922_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtEnd',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtStart',
            field=models.DateField(auto_now=True),
        ),
    ]
