# Generated by Django 3.0.8 on 2020-09-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_auto_20200922_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrauser',
            old_name='canSponsor',
            new_name='acceptSponsor',
        ),
    ]
