# Generated by Django 3.0.8 on 2020-09-24 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0013_auto_20200924_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauser',
            name='sponsorOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alumni.ExtraUser'),
        ),
    ]
