# Generated by Django 3.0.8 on 2020-09-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_extrauser_sponsorof'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='earning',
            field=models.IntegerField(default=None, help_text='Revenu percu brut pour la durée annoncée', null=True),
        ),
    ]
