# Generated by Django 3.0.8 on 2020-09-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0015_work_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofwork',
            name='owner',
            field=models.CharField(default='public', max_length=150),
        ),
    ]
