# Generated by Django 3.0.8 on 2020-10-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0016_pieceofwork_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='title',
            field=models.TextField(default='sans titre', help_text="Titre de l'oeuvre, même temporaire", unique=True),
        ),
    ]
