# Generated by Django 3.0.8 on 2020-10-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0017_auto_20201001_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
