# Generated by Django 3.0.8 on 2020-10-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0018_profil_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='town',
            field=models.TextField(null=True),
        ),
    ]
