# Generated by Django 3.0.8 on 2020-10-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0019_profil_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='dtLastUpdate',
            field=models.DateField(auto_now=True),
        ),
    ]
