# Generated by Django 3.0.8 on 2020-10-07 09:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0021_extrauser_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('pieceofwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alumni.PieceOfWork')),
                ('duration', models.DurationField(help_text='Durée du film', null=True)),
            ],
            bases=('alumni.pieceofwork',),
        ),
        migrations.RemoveField(
            model_name='pieceofwork',
            name='imdb',
        ),
        migrations.RemoveField(
            model_name='pieceofwork',
            name='text_url',
        ),
        migrations.RemoveField(
            model_name='pieceofwork',
            name='url',
        ),
        migrations.AddField(
            model_name='pieceofwork',
            name='files',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Liens vers des documents attaché', null=True),
        ),
        migrations.AddField(
            model_name='pieceofwork',
            name='urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text="Liens vers des références externes à l'oeuvre", null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='biography',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='budget',
            field=models.IntegerField(default=0, help_text="Coût total de réalisation de l'oeuvre"),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtEnd',
            field=models.DateField(auto_now=True, help_text="Date de fin de la réalisation de l'oeuvre"),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtStart',
            field=models.DateField(auto_now=True, help_text="Date de début de la réalisation de l'oeuvre"),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='nature',
            field=models.CharField(choices=[('MOVIE', 'Film long métrage'), ('COURT', 'Court métrage'), ('PUB', 'Publicité'), ('CORP', "Film d'entreprise"), ('SONG', 'Single/Album')], default='MOVIE', help_text="Classification de l'oeuvre", max_length=20),
        ),
    ]
