# Generated by Django 3.0.8 on 2020-10-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0022_auto_20201007_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pieceofwork',
            old_name='urls',
            new_name='links',
        ),
    ]
