# Generated by Django 3.0.8 on 2020-10-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0023_auto_20201007_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofwork',
            name='description',
            field=models.TextField(help_text="Description/Resumer de l'oeuvre", null=True),
        ),
    ]
