# Generated by Django 3.0.8 on 2020-10-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0024_pieceofwork_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='description',
            field=models.TextField(help_text="Description/Resumer de l'oeuvre", max_length=3000, null=True),
        ),
    ]
