# Generated by Django 3.0.8 on 2020-10-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0025_auto_20201007_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofwork',
            name='visual',
            field=models.TextField(blank=True, help_text="Visuel de l'oeuvre"),
        ),
    ]
