# Generated by Django 3.0.8 on 2020-10-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0026_pieceofwork_visual'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofwork',
            name='category',
            field=models.TextField(help_text='Liste des categories auxquelles appartient le film', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pieceofwork',
            name='lang',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
