# Generated by Django 3.0.8 on 2020-10-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0027_auto_20201007_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='title',
            field=models.CharField(default='sans titre', help_text="Titre de l'oeuvre, même temporaire", max_length=300, unique=True),
        ),
    ]
