# Generated by Django 3.0.8 on 2020-10-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0028_auto_20201007_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofwork',
            name='year',
            field=models.IntegerField(help_text='Année de sortie', null=True),
        ),
    ]
