# Generated by Django 3.0.8 on 2020-10-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0030_auto_20201008_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='dtLastNotif',
            field=models.DateField(auto_now=True, help_text='Date de la dernière notification envoyé'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='dtLastUpdate',
            field=models.DateField(auto_now=True, help_text='Date de la dernière modification du profil'),
        ),
    ]
