# Generated by Django 3.0.8 on 2020-10-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0031_auto_20201014_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='obsolescenceScore',
            field=models.IntegerField(default=0, help_text="Indique le degré d'obsolescence probable"),
        ),
    ]
