# Generated by Django 3.0.8 on 2020-10-17 22:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0034_profil_auto_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='auto_updates',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Date de mise a jour', null=True),
        ),
    ]
