# Generated by Django 3.0.8 on 2020-10-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0035_auto_20201018_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='auto_updates',
            field=models.CharField(default='0,0,0,0,0,0', help_text='Date de mise a jour', max_length=300),
        ),
    ]
