# Generated by Django 3.0.8 on 2020-10-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0036_auto_20201018_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='address',
            field=models.CharField(help_text='Adresse postale, rue', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='department',
            field=models.CharField(default='', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='firstname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
