# Generated by Django 3.0.8 on 2020-10-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0038_profil_cursus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='department',
            field=models.CharField(default='', max_length=60, null=True),
        ),
    ]
