# Generated by Django 3.0.8 on 2020-10-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0040_auto_20201021_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
