# Generated by Django 3.0.8 on 2020-10-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0042_auto_20201022_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
