# Generated by Django 3.0.8 on 2020-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0044_auto_20201022_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='job',
            field=models.CharField(default='', max_length=60, null=True),
        ),
    ]
