# Generated by Django 3.0.8 on 2020-10-22 16:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0045_profil_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='advices',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text="Le système fourni des conseils pour augmenter le rayonnement d'une personne", null=True),
        ),
    ]
