# Generated by Django 3.0.8 on 2020-10-23 11:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0046_profil_advices'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauser',
            name='ask',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None),
        ),
        migrations.AddField(
            model_name='extrauser',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None),
        ),
    ]
