# Generated by Django 3.0.8 on 2020-10-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0048_work_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='dtEnd',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='dtStart',
            field=models.DateField(null=True),
        ),
    ]
