# Generated by Django 3.0.8 on 2020-11-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0049_auto_20201027_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='description',
            field=models.TextField(default='', help_text="Description/Resumer de l'oeuvre", max_length=3000),
        ),
    ]
