# Generated by Django 3.0.8 on 2020-11-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0050_auto_20201118_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='nature',
            field=models.CharField(default='MOVIE', help_text="Classification de l'oeuvre", max_length=20),
        ),
    ]
