# Generated by Django 3.0.8 on 2020-11-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0051_auto_20201119_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='pow',
        ),
    ]
