# Generated by Django 3.0.8 on 2020-11-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0052_remove_work_pow'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='pow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='alumni.PieceOfWork'),
        ),
    ]
