# Generated by Django 3.0.8 on 2020-11-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0053_work_pow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='pow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='alumni.PieceOfWork'),
        ),
    ]
