# Generated by Django 3.0.8 on 2020-12-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0056_auto_20201216_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
