# Generated by Django 3.0.11 on 2021-01-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0058_auto_20210105_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse postale, rue', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='cp',
            field=models.CharField(blank=True, help_text='Adresse postale, code postal', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='town',
            field=models.CharField(blank=True, help_text='Adresse postale, ville', max_length=50, null=True),
        ),
    ]
