# Generated by Django 3.0.11 on 2021-01-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0059_auto_20210105_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='department',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='mobile',
            field=models.CharField(blank=True, default='06', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nationality',
            field=models.CharField(blank=True, default='Française', max_length=30),
        ),
    ]
