# Generated by Django 3.0.11 on 2021-01-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0060_auto_20210105_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauser',
            name='profil_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
