# Generated by Django 3.0.11 on 2021-01-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0062_auto_20210114_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='validate',
            field=models.BooleanField(default=False, help_text="Indique si l'expérience est validé ou pas"),
        ),
    ]
