# Generated by Django 3.0.11 on 2021-01-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0064_work_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='source',
            field=models.CharField(default='', help_text="source ayant permis d'identifier le projet : imdb, unifrance, bellefaye, manuel", max_length=100),
        ),
    ]
