# Generated by Django 3.0.11 on 2021-01-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0065_auto_20210120_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='dtLastSearch',
            field=models.DateField(auto_now=True, help_text="Date de la dernière recherche d'expérience pour le profil"),
        ),
    ]
