# Generated by Django 3.0.11 on 2021-01-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0066_profil_dtlastsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='dtEnd',
        ),
        migrations.RemoveField(
            model_name='work',
            name='dtStart',
        ),
        migrations.AlterField(
            model_name='profil',
            name='dtLastNotif',
            field=models.DateTimeField(auto_now=True, help_text='Date de la dernière notification envoyé'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='dtLastSearch',
            field=models.DateTimeField(auto_now=True, help_text="Date de la dernière recherche d'expérience pour le profil"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='dtLastUpdate',
            field=models.DateTimeField(auto_now=True, help_text='Date de la dernière modification du profil'),
        ),
    ]
