# Generated by Django 3.0.11 on 2021-02-15 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0067_auto_20210121_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofwork',
            name='dtCreate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
