# Generated by Django 3.0.11 on 2021-03-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0068_pieceofwork_dtcreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtCreate',
            field=models.DateField(auto_now_add=True, help_text="Date de création de l'oeuvre"),
        ),
    ]
